// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izejzglvtbsfbdavryxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6ZWp6Z2x2dGJzZmJkYXZyeXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzMxMzcsImV4cCI6MjA3Mzc0OTEzN30.WUcNgyCNtVytVyhIXJlZGFUquMizi9eygKbR4FVtSBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});